"""tas index big-trades — add condition + sweep/block/financing + leg_group to tas_prints

Revision ID: 0041
Revises: e4a7c2f9b1d3
Create Date: 2026-08-04

Hand-written (NOT autogenerated) — adds ONLY five nullable columns to
``tas_prints`` so the market-wide-tape collector can persist the observed
``exchange_sale_conditions`` code and the structure tags derived from it
(sweep / block / deep-ITM financing) plus a same-poll ``leg_group`` cluster id.
Autogenerate is unsafe on this schema (models drift from the live DB), so this
is hand-written exactly like ``c71d5f34fa9c``. All columns nullable → safe
additive change; existing rows keep NULLs.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0041"
down_revision: Union[str, None] = "e4a7c2f9b1d3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_TABLE = "tas_prints"


def upgrade() -> None:
    op.add_column(_TABLE, sa.Column("condition", sa.String(length=8), nullable=True))
    op.add_column(_TABLE, sa.Column("is_sweep", sa.Boolean(), nullable=True))
    op.add_column(_TABLE, sa.Column("is_block", sa.Boolean(), nullable=True))
    op.add_column(_TABLE, sa.Column("is_financing", sa.Boolean(), nullable=True))
    op.add_column(_TABLE, sa.Column("leg_group", sa.String(length=24), nullable=True))
    op.create_index("ix_tas_prints_leg_group", _TABLE, ["leg_group"])


def downgrade() -> None:
    op.drop_index("ix_tas_prints_leg_group", table_name=_TABLE)
    op.drop_column(_TABLE, "leg_group")
    op.drop_column(_TABLE, "is_financing")
    op.drop_column(_TABLE, "is_block")
    op.drop_column(_TABLE, "is_sweep")
    op.drop_column(_TABLE, "condition")
