"""swing dossier — kpi_snapshots + short_interest_snapshots

Revision ID: 0042
Revises: 0041
Create Date: 2026-08-06

Hand-written (NOT autogenerated — models drift from the live DB, autogenerate is
destructive on this schema; see 0041 / c71d5f34fa9c). Two additive tables for the
swing-earnings dossier, both idempotent-upsert keyed (rule 5), descriptive only
(rule 4):

* ``kpi_snapshots`` — per-quarter operating KPIs pulled from the call transcript
  (DBNRR/cRPO/margin/customer-counts) so the scorecard shows a trend, not a point.
* ``short_interest_snapshots`` — FINRA short data (daily Reg SHO short-volume
  proxy now; settled bi-monthly SI + days-to-cover when FINRA API creds are set).

Round-trips cleanly: ``alembic downgrade -1 && alembic upgrade head``.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0042"
down_revision: Union[str, None] = "0041"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "kpi_snapshots",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("period_label", sa.String(length=16), nullable=False),  # e.g. "2026Q1"
        sa.Column("ts", sa.Date(), nullable=False),
        sa.Column("dbnrr_pct", sa.Float(), nullable=True),
        sa.Column("revenue_growth_yoy_pct", sa.Float(), nullable=True),
        sa.Column("gross_margin_pct", sa.Float(), nullable=True),
        sa.Column("operating_margin_pct", sa.Float(), nullable=True),
        sa.Column("crpo_growth_yoy_pct", sa.Float(), nullable=True),
        sa.Column("rpo_growth_yoy_pct", sa.Float(), nullable=True),
        sa.Column("customers_over_100k", sa.Float(), nullable=True),
        sa.Column("customers_over_1m", sa.Float(), nullable=True),
        sa.Column("fcf_margin_pct", sa.Float(), nullable=True),
        sa.Column("guidance_direction", sa.String(length=16), nullable=True),
        sa.Column("one_line_kpi_read", sa.String(length=256), nullable=True),
        sa.Column("source", sa.String(length=32), nullable=True),
        sa.UniqueConstraint("symbol", "period_label", name="uq_kpi_symbol_period"),
    )
    op.create_index("ix_kpi_snapshots_symbol", "kpi_snapshots", ["symbol"])

    op.create_table(
        "short_interest_snapshots",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("ts", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),  # "regsho_daily" | "finra_si"
        sa.Column("short_volume", sa.Float(), nullable=True),
        sa.Column("total_volume", sa.Float(), nullable=True),
        sa.Column("short_volume_ratio", sa.Float(), nullable=True),
        sa.Column("short_volume_ratio_avg", sa.Float(), nullable=True),
        sa.Column("short_interest", sa.Float(), nullable=True),
        sa.Column("avg_daily_volume", sa.Float(), nullable=True),
        sa.Column("days_to_cover", sa.Float(), nullable=True),
        sa.Column("settlement_date", sa.Date(), nullable=True),
        sa.UniqueConstraint("symbol", "ts", "source", name="uq_shortint_symbol_ts_source"),
    )
    op.create_index("ix_short_interest_snapshots_symbol", "short_interest_snapshots", ["symbol"])


def downgrade() -> None:
    op.drop_index("ix_short_interest_snapshots_symbol", table_name="short_interest_snapshots")
    op.drop_table("short_interest_snapshots")
    op.drop_index("ix_kpi_snapshots_symbol", table_name="kpi_snapshots")
    op.drop_table("kpi_snapshots")
