"""breadth_snapshots — daily market breadth + Norseman Bull/Bear Line + divergence

Revision ID: 0043
Revises: 0042
Create Date: 2026-08-11

Hand-written (NOT autogenerated — models drift from the live DB, autogenerate is
destructive on this schema; see 0041 / 0042). One additive table, idempotent-upsert
keyed on (ts, source), descriptive only (rule 4):

* ``breadth_snapshots`` — one row per day: S&P-wide advancers/decliners, the
  CUMULATIVE A-D line, % above 50/200-day MA, new-highs/lows, McClellan
  oscillator + summation, plus the Norseman Bull/Bear Line (0.90 × running-max
  weekly SPX-equivalent close) and the A-D-line-vs-price divergence read. Feeds
  the synthesis engine + the Norseman regime overlay.

Round-trips cleanly: ``alembic downgrade -1 && alembic upgrade head``.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0043"
down_revision: Union[str, None] = "0042"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "breadth_snapshots",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("ts", sa.Date(), nullable=False),
        sa.Column("source", sa.String(length=24), nullable=False),  # "fmp_sp500"
        # constituent breadth
        sa.Column("advancers", sa.Integer(), nullable=True),
        sa.Column("decliners", sa.Integer(), nullable=True),
        sa.Column("net_adv", sa.Integer(), nullable=True),
        sa.Column("ad_line", sa.Float(), nullable=True),  # cumulative A-D line
        sa.Column("new_highs", sa.Integer(), nullable=True),
        sa.Column("new_lows", sa.Integer(), nullable=True),
        sa.Column("pct_above_50", sa.Integer(), nullable=True),
        sa.Column("pct_above_200", sa.Integer(), nullable=True),
        sa.Column("mcclellan_osc", sa.Float(), nullable=True),
        sa.Column("mcclellan_sum", sa.Float(), nullable=True),
        sa.Column("n_constituents", sa.Integer(), nullable=True),
        # regime line (Norseman Bull/Bear Line, SPX-equivalent)
        sa.Column("spx_close", sa.Float(), nullable=True),
        sa.Column("bull_bear_line", sa.Float(), nullable=True),
        sa.Column("above_bbl", sa.Boolean(), nullable=True),
        # breadth-vs-price divergence
        sa.Column("divergence_state", sa.String(length=16), nullable=True),
        sa.Column("divergence_len", sa.Integer(), nullable=True),
        sa.UniqueConstraint("ts", "source", name="uq_breadth_ts_source"),
    )
    op.create_index("ix_breadth_snapshots_ts", "breadth_snapshots", ["ts"])


def downgrade() -> None:
    op.drop_index("ix_breadth_snapshots_ts", table_name="breadth_snapshots")
    op.drop_table("breadth_snapshots")
