"""newsletter_levels + newsletter_scenarios — structured levels + if-then from letters

Revision ID: 0044
Revises: 0043
Create Date: 2026-08-11

Hand-written (NOT autogenerated — see 0042/0043). Two additive tables the
local-Ollama ``synthesis.newsletter_extract`` pass fills from the stored letter
bodies (Doc / VolSignals / Kurt / Norseman), both idempotent-upsert keyed, both
descriptive only (rule 4):

* ``newsletter_levels`` — one row per stated level (gamma flip / call-put walls /
  Bull-Bear Line / expected move / …), for cross-checking vs our computed values.
* ``newsletter_scenarios`` — one row per stated IF-THEN scenario (Doc's "if vol
  X → price Y"), for the synthesis engine's trigger layer.

Round-trips cleanly: ``alembic downgrade -1 && alembic upgrade head``.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0044"
down_revision: Union[str, None] = "0043"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "newsletter_levels",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("source", sa.String(length=24), nullable=False),  # DOC | VOLSIGNALS | KURT | NORSEMAN
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("name", sa.String(length=40), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(length=12), nullable=True),
        sa.Column("note", sa.String(length=160), nullable=True),
        sa.UniqueConstraint("source", "as_of", "name", name="uq_nl_source_asof_name"),
    )
    op.create_index("ix_newsletter_levels_source", "newsletter_levels", ["source"])

    op.create_table(
        "newsletter_scenarios",
        sa.Column("id", sa.BigInteger(), primary_key=True, autoincrement=True),
        sa.Column("source", sa.String(length=24), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("idx", sa.Integer(), nullable=False),
        sa.Column("trigger", sa.String(length=256), nullable=False),
        sa.Column("consequence", sa.String(length=256), nullable=True),
        sa.Column("direction", sa.String(length=12), nullable=True),
        sa.Column("confidence", sa.String(length=12), nullable=True),
        sa.UniqueConstraint("source", "as_of", "idx", name="uq_ns_source_asof_idx"),
    )
    op.create_index("ix_newsletter_scenarios_source", "newsletter_scenarios", ["source"])


def downgrade() -> None:
    op.drop_index("ix_newsletter_scenarios_source", table_name="newsletter_scenarios")
    op.drop_table("newsletter_scenarios")
    op.drop_index("ix_newsletter_levels_source", table_name="newsletter_levels")
    op.drop_table("newsletter_levels")
