"""gex_transition_daily (dealer-gamma "quiet unwind" state series)

Revision ID: 0045
Revises: 0044
Create Date: 2026-08-11

Hand-written (NOT autogenerated — MEMORY/build-queue standing rule). Additive;
creates ONLY the ``gex_transition_daily`` table (one EOD row per symbol/day:
net GEX, ΔGEX z, clean ATM IV, ΔIV, classified state, and slots for forward
returns). No drops/alters. Descriptor / research track (FlashAlpha rule 4).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0045"
down_revision: Union[str, None] = "0044"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "gex_transition_daily",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("ts", sa.Date(), nullable=False),
        sa.Column("net_gex", sa.Float(), nullable=True),
        sa.Column("d_gex", sa.Float(), nullable=True),
        sa.Column("d_gex_z", sa.Float(), nullable=True),
        sa.Column("atm_iv", sa.Float(), nullable=True),
        sa.Column("d_iv_pt", sa.Float(), nullable=True),
        sa.Column("state", sa.String(length=24), nullable=True),
        sa.Column("spot", sa.Float(), nullable=True),
        sa.Column("flip", sa.Float(), nullable=True),
        sa.Column("fwd5", sa.Float(), nullable=True),
        sa.Column("fwd10", sa.Float(), nullable=True),
        sa.Column("fwd21", sa.Float(), nullable=True),
        sa.Column("source", sa.String(length=48), nullable=False, server_default="gamma_history+iv_tenor"),
        sa.UniqueConstraint("symbol", "ts", name="uq_gex_transition_daily"),
    )
    op.create_index("ix_gex_transition_daily_ts", "gex_transition_daily", ["ts"])


def downgrade() -> None:
    op.drop_index("ix_gex_transition_daily_ts", table_name="gex_transition_daily")
    op.drop_table("gex_transition_daily")
