"""vol_surface_cm (constant-maturity delta-vol surface — the ^SPX board)

Revision ID: 0046
Revises: 0045
Create Date: 2026-08-11

Hand-written (NOT autogenerated — MEMORY/build-queue standing rule). Additive;
creates ONLY the ``vol_surface_cm`` table (constant-maturity IV smile per rung /
delta / wing, for the vol-surface-changes board). No drops/alters. Descriptor
(FlashAlpha rule 4).
"""

from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0046"
down_revision: Union[str, None] = "0045"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "vol_surface_cm",
        sa.Column("id", sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column("symbol", sa.String(length=16), nullable=False),
        sa.Column("ts", sa.Date(), nullable=False),
        sa.Column("dte", sa.Integer(), nullable=False),
        sa.Column("delta", sa.Float(), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("iv", sa.Float(), nullable=True),
        sa.Column("spot", sa.Float(), nullable=True),
        sa.Column("near_expiry", sa.Date(), nullable=True),
        sa.UniqueConstraint("symbol", "ts", "dte", "delta", "side", name="uq_vol_surface_cm"),
    )
    op.create_index("ix_vol_surface_cm_symbol_ts", "vol_surface_cm", ["symbol", "ts"])


def downgrade() -> None:
    op.drop_index("ix_vol_surface_cm_symbol_ts", table_name="vol_surface_cm")
    op.drop_table("vol_surface_cm")
