"""sector correlation snapshots

Revision ID: b7d2c1a9f3e6
Revises: c71d5f34fa9c
Create Date: 2026-07-30

Hand-written (NOT autogenerated) — creates only the sector_corr_snapshots table.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'b7d2c1a9f3e6'
down_revision: Union[str, None] = 'c71d5f34fa9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'sector_corr_snapshots',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('as_of', sa.Date(), nullable=False),
        sa.Column('avg_corr_21', sa.Float(), nullable=True),
        sa.Column('avg_corr_63', sa.Float(), nullable=True),
        sa.Column('dispersion', sa.Float(), nullable=True),
        sa.Column('n_etfs', sa.Integer(), nullable=True),
        sa.Column('matrix', sa.JSON(), nullable=True),
        sa.Column('computed_at', sa.DateTime(), nullable=True),
        sa.Column('source', sa.String(length=32), nullable=False, server_default='yfinance'),
        sa.UniqueConstraint('as_of', 'source', name='uq_sector_corr_snap'),
    )


def downgrade() -> None:
    op.drop_table('sector_corr_snapshots')
