"""cockpit fields — add dex_flip + put/call volume + delta-notional to greeks_snapshots

Revision ID: c71d5f34fa9c
Revises: 0040
Create Date: 2026-07-30

Hand-written (NOT autogenerated) — adds ONLY the five cockpit columns to
greeks_snapshots. Autogenerate is unsafe on this schema (models drift from the
live DB), so future column adds should also be hand-written like this.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'c71d5f34fa9c'
down_revision: Union[str, None] = '0040'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('greeks_snapshots', sa.Column('dex_flip', sa.Float(), nullable=True))
    op.add_column('greeks_snapshots', sa.Column('call_volume', sa.Float(), nullable=True))
    op.add_column('greeks_snapshots', sa.Column('put_volume', sa.Float(), nullable=True))
    op.add_column('greeks_snapshots', sa.Column('call_notional', sa.Float(), nullable=True))
    op.add_column('greeks_snapshots', sa.Column('put_notional', sa.Float(), nullable=True))


def downgrade() -> None:
    op.drop_column('greeks_snapshots', 'put_notional')
    op.drop_column('greeks_snapshots', 'call_notional')
    op.drop_column('greeks_snapshots', 'put_volume')
    op.drop_column('greeks_snapshots', 'call_volume')
    op.drop_column('greeks_snapshots', 'dex_flip')
