"""sector snapshots (skew + walls + fixed-strike iv)

Revision ID: e4a7c2f9b1d3
Revises: b7d2c1a9f3e6
Create Date: 2026-07-30

Hand-written (NOT autogenerated — see MEMORY/build-queue standing rule): creates
ONLY the sector_snapshots table (per-SPDR 25Δ skew, call/put walls, near-money
per-strike IV grid for the fixed-strike footprint). Additive; no drops/alters.
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'e4a7c2f9b1d3'
down_revision: Union[str, None] = 'b7d2c1a9f3e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        'sector_snapshots',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('as_of', sa.Date(), nullable=False),
        sa.Column('symbol', sa.String(length=16), nullable=False),
        sa.Column('spot', sa.Float(), nullable=True),
        sa.Column('net_gex', sa.Float(), nullable=True),
        sa.Column('net_dex', sa.Float(), nullable=True),
        sa.Column('gex_flip', sa.Float(), nullable=True),
        sa.Column('atm_iv', sa.Float(), nullable=True),
        sa.Column('rr25', sa.Float(), nullable=True),
        sa.Column('rr25_dte', sa.Integer(), nullable=True),
        sa.Column('call_wall', sa.Float(), nullable=True),
        sa.Column('put_wall', sa.Float(), nullable=True),
        sa.Column('strike_iv', sa.JSON(), nullable=True),
        sa.Column('computed_at', sa.DateTime(), nullable=True),
        sa.Column('source', sa.String(length=32), nullable=False, server_default='cvforge'),
        sa.UniqueConstraint('as_of', 'symbol', 'source', name='uq_sector_snap'),
    )


def downgrade() -> None:
    op.drop_table('sector_snapshots')
