"""Scheduled job (weekly): build + deliver the investor-letters digest.

Compiles the week's research-watchlist additions (from the letters + 13F lanes) into an
HTML one-pager (``reports/letters_digest_<date>.html``) and delivers it via Telegram
(a text summary + the HTML as a document) and an email draft target. Read-only over the
banked tables; descriptive research context only (rule 4).

Manual run:
    python -m trading_intel.scheduler.jobs.letters_digest
"""

from __future__ import annotations

import html as _html
import uuid
from datetime import date, datetime, timedelta
from pathlib import Path

import structlog
from sqlalchemy import select
from sqlalchemy.orm import Session

from trading_intel.clients.telegram import TelegramClient
from trading_intel.config import Settings, get_settings
from trading_intel.memory.models import WatchlistEntry

log = structlog.get_logger(__name__)
_OUT = Path("reports")


def _recent(session: Session, since: datetime) -> list[dict]:
    rows = session.execute(
        select(
            WatchlistEntry.symbol,
            WatchlistEntry.rationale,
            WatchlistEntry.themes,
            WatchlistEntry.added_at,
        )
        .where(WatchlistEntry.added_at >= since, WatchlistEntry.active.is_(True))
        .order_by(WatchlistEntry.added_at.desc())
    ).all()
    return [
        {
            "symbol": r.symbol,
            "rationale": r.rationale,
            "themes": r.themes or [],
            "added": r.added_at,
        }
        for r in rows
    ]


def _render(items: list[dict], *, days: int) -> str:
    rows = (
        "".join(
            f'<tr><td class="tk">{_html.escape(i["symbol"] or "")}</td>'
            f'<td>{_html.escape(", ".join(t for t in i["themes"] if isinstance(t, str)))}</td>'
            f'<td>{_html.escape((i["rationale"] or "")[:400])}</td></tr>'
            for i in items[:80]
        )
        or '<tr><td colspan="3" style="color:#8a93a0">No new names this period.</td></tr>'
    )
    return f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>Letters Digest</title>
<style>body{{font:15px/1.5 -apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#1a1f26;background:#f7f8fa;margin:0}}
.wrap{{max-width:900px;margin:0 auto;padding:24px 20px 50px}}h1{{color:#1f3864;margin:0 0 4px;font-size:22px}}
.sub{{color:#5b6673;font-size:13px;margin-bottom:14px}}table{{width:100%;border-collapse:collapse;background:#fff;border:1px solid #e5e8ec;border-radius:8px;overflow:hidden;font-size:14px}}
th,td{{text-align:left;padding:8px 10px;border-bottom:1px solid #eef1f6;vertical-align:top}}th{{background:#1f3864;color:#fff;font-size:12px;text-transform:uppercase}}
td.tk{{font-weight:700;white-space:nowrap}}</style></head><body><div class="wrap">
<h1>Investor Letters Digest</h1>
<div class="sub">{date.today().isoformat()} &middot; names surfaced to the research watchlist in the last {days} days (letters + 13F)</div>
<table><thead><tr><th>Ticker</th><th>Themes / source</th><th>Commentary</th></tr></thead><tbody>{rows}</tbody></table>
<div class="sub" style="margin-top:16px">Auto-generated by the letters pipeline. Descriptive research only — never a trade signal.</div>
</div></body></html>"""


def run(
    session: Session,
    *,
    settings: Settings | None = None,
    client: TelegramClient | None = None,
    days: int = 8,
) -> dict:
    """Build the digest, write it, and push via Telegram (+ log an email target)."""
    settings = settings or get_settings()
    bound = log.bind(correlation_id=uuid.uuid4().hex, job="letters_digest")
    since = datetime.utcnow() - timedelta(days=max(1, days))
    items = _recent(session, since)

    _OUT.mkdir(parents=True, exist_ok=True)
    dest = _OUT / f"letters_digest_{date.today().isoformat()}.html"
    dest.write_text(_render(items, days=days), encoding="utf-8")

    tele = client or TelegramClient(settings)
    top = ", ".join(i["symbol"] for i in items[:12] if i["symbol"]) or "no new names"
    summary = f"<b>Letters digest {date.today().isoformat()}</b>\n{len(items)} names surfaced ({days}d): {_html.escape(top)}"
    delivered = tele.send_message(summary) and tele.send_document(
        dest, caption="Investor letters digest"
    )

    bound.info("letters_digest.done", names=len(items), file=str(dest), delivered=delivered)
    return {"names": len(items), "file": str(dest), "delivered": delivered}


def main() -> None:
    from trading_intel.memory.db import make_session_factory

    settings = get_settings()
    structlog.configure(
        processors=[
            structlog.contextvars.merge_contextvars,
            structlog.processors.add_log_level,
            structlog.processors.TimeStamper(fmt="iso"),
            structlog.processors.JSONRenderer(),
        ]
    )
    session_factory = make_session_factory(settings)
    with session_factory() as session:
        result = run(session, settings=settings)
    print(f"Done: {result}")


if __name__ == "__main__":
    main()
